language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python bot.py
env:
  - secure: "m6W7T90kCAP0HrgK/a/m4UsvLUBlJZYSb6Iv7BdM4uoUjb0IxhJFeihxBkHYKz6GdkaitQrSi+NdL4wIQqjbxH2BG1ebE7G+9bx9KnlwPhHGvTWwKJGUxqS+1Hk3QlVjV12NZJVlJrzHh5qtbv9K8UIRpKNX+/g13avpe5PRmnB1cwxS+Wui5En15xlI8OhSAAJxWGxtyiPfS29YVYSPrqliNjNO20FD04yH4P2LNKBufBlJSIq//qUDDjutgzuikb199r0RZeDVTg/fhI8oyWRkoyhynbi/S+4yqoT8JWzEocgVVPhM5rz4dOnhEM85aGOjNW8vQuw+VMNRwLVS7H503Yb2tF1NUJk8k46B0vCs5l52SsFsVkaU2gl6ySygP0FYn6XaJQv7Pa3XFFfAGzYUDPYVqohxe95U40HdfELd++wTZUkzBX5LeRN0jc0NhAATS3nrv2W5DXeuz5PtDx8xYsKgRGuF+dDoyrwYSMzMUFy+wPwps/cXR5jA9bS/mDqZ1hnN9lyPDQ/cOUXGN2MKGHqwbemsxKqewtGvnncpbZOKKmT4CmHXYYZuqkz3ihLfLc+J5ecxJ0XN6imn7YhwXjUKg17SffRHDfu/TMYDOyk/qEEh2oLRxe7NgI2xl/uoIE3/c9uOx16oPGrP2rYPh1+kYaXmkpez2B7vuDs="
