language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python bot.py
secure: "ez9W1tCG1TG+N2GDf4TQ5wGRjbGvJwxytuFCcxty+luf7N1wKMo4nUFDPpFwJu/yFbSetXaXC+XslUdeDnKgzGESbW77nfVYdmKm4NkpXspQSaE22SGZQdAgfp/vDFC6d3PTZHI8qvwfpJNDGbpnRBOHKunTg7BUz3DudENbwxQrk/1tYxV5kErox+ECAXzGOTAsveVUGDy7PLutetxe14XCpKa+H6BdVfqVEwjS3KRrw7PJOWil8KxKY+qQscyYLzvoLLV3mYz2vR744eQhdLb7y7igaSSgXoZQwWGAza0n1e3dfh4FBncl3rcDQfquKdnrk+scoFIcAuwGAJgHS0KbHlp/oTxazNTRq+0Z5Pk7NsaSU2iXX57fYaDHRBsNmjvBDFclH+IlctIVUPTTv2A5paG6Qw5GPPmbB6OIphqqSrWBLC2QpaPjzVo4TdM61OwOXYjdQBbRD2EHG8En5LbFYjLiWfLewjyxkBYnXZrN2oU3ZTcdIEPiJmqUtw81PpmOwea3+wjYSPXKPW5zH17IvkVAgnfZ8DALe1Cy/tyYnCIjkl8FHmoKH54kT5i2gpP9SYndto4XywC86xACubNJMiVt/ECC1pNNWEyY7kh6XNQu7+820Y9awW33zs9d0k2e7ujvL06Di4vl8is67y6vCZsj63wxqMsxSTHhtqc="
